In [3]:
#!pip install transformers tensorflow

from transformers import BertTokenizer, TFBertModel, pipeline
import tensorflow as tf
import numpy as np

/home/vscode/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-05-12 08:32:33.128508: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-12 08:32:33.133224: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-12 08:32:33.185122: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-12 08:32:33.187344: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical opera

In [4]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [5]:
model.summary()

Model: "tf_bert_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
Total params: 109,482,240
Trainable params: 109,482,240
Non-trainable params: 0
_________________________________________________________________


In [41]:
def embed(text):
  encoded_input = tokenizer("[CLS]" + text + "[SEP]", return_tensors='tf')
  return model(encoded_input).last_hidden_state

def similarity(a, b):
  return np.sqrt(np.sum((a-b)**2))

res = embed("a http server on port 3000 with parameters username of type string").numpy()
# res = embed("At the UvA we research microservices architectures for the sake of humanity").numpy()
http = embed('http server').numpy()
print(similarity(res[0][2], http[0][1]))

17.240368


In [ ]:
man = embed("man").numpy()
king = embed("king").numpy()
woman = embed("woman").numpy()
queen = embed('queen').numpy()

test = woman + (king - man)
print(queen)

print(np.sqrt(np.sum((queen-test)**2)))

{'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 101,  101, 2158,  102,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>}
{'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 101,  101, 2332,  102,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>}
{'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 101,  101, 2450,  102,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>}
{'input_ids': <tf.Tensor: shape=(1, 5), 